BASE: ['']
TOOLBOX_MODE: "rPPG_removal"      # "train_and_test", "only_test" or "rPPG_removal"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 15
  LR: 1e-3
  MODEL_FILE_NAME: PURE_PURE_UBFC_tscan
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False              # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/local/home/vbozic/PURE_dataset/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/local/home/vbozic/PURE_dataset/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS :
      DATA_TYPE: [ 'Standardized','Normalized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: True
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.2
      H: 72
      W: 72
VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/local/home/vbozic/PURE_dataset/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/local/home/vbozic/PURE_dataset/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Standardized','Normalized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: True
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.2
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson','SNR']
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/local/home/vbozic/PURE_dataset/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/local/home/vbozic/PURE_dataset/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Standardized','Normalized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: True
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.2
      H: 72
      W: 72 
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 3
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 20
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  MODEL_PATH:   "/local/home/vbozic/rPPG-Toolbox/PreTrainedModels/PURE_SizeW72_SizeH72_ClipLength180_DataTypeStandardized_Normalized_LabelTypeNormalized_Large_boxTrue_Large_size1.2_Dyamic_DetTrue_det_len180/PURE_PURE_UBFC_tscan_Epoch13.pth"
 